repos:
    - repo: local
      hooks:
          - id: oxlint
            name: oxlint (type-aware)
            entry: pnpm exec oxlint --type-aware --fix
            language: system
            files: \.(js|ts|mts|cts|svelte)$
            pass_filenames: false
          # svelte-check would always run on all files
          # - id: svelte-check
          #   name: svelte-check
          #   entry: pnpm exec svelte-check --tsconfig ./tsconfig.json --diagnostic-sources svelte
          #   language: system
          #   files: \.(svelte|svelte\.ts)$
          #   pass_filenames: false
